# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipography',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab2.Discography'),
        ),
    ]
